### ISSUE TITLE
Provide processed version number

### ISSUE THREAD

**Issue by sdruskat** [hermes-hmc/workflow#67]
There are potentially many "version identifiers" for a single version (timestamp, version string (`v1.0.3`), etc.).
For publication, we need one version identifier.

Includes deduplication, e.g., cff-provided version vs. tag vs. ...

In this processing step, this version identifier will be defined.
This processing step should also allow a configuration, where a `reserved` tag or similar is used to trigger the workflow, which will then, however, extract the real version from the tag. This real version will be used for publication, and could also be used in post-processing to tag the published commit.

**Comment by led02** [comment]
With #154 almost merged, we can continue here...

- Implement a processing step "set_version"
- configure which alternate version to select

*thoght:* This could also implemented in an abstract way as a processor (e.g., not only making the precedence configurable but also the key for which this rule should be applied). Also, this could be already decided during the merging of the models.

```toml
[process]
use = [ "select_alternative" ]

[process.select_alternative."version"]
precedence = [ "cff", "codemeta" ]
```
